services:
  remember:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/initMySQL.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  